server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: parking-space-service
          uri: lb://parking-space-service
          predicates:
            - Path=/api/spaces/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicles/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
