server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicles/**

        - id: parking-space-service
          uri: lb://parking-space-service
          predicates:
            - Path=/api/spaces/**

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**

        - id: payment-service
          uri: http://localhost:5005
          predicates:
            - Path=/api/payments/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
