server:
  port: 8082

spring:
  application:
    name: parking-space-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/parking_db
    username: root
    password: 0909
    driver-class-name: com.mysql.cj.jdbc.Driver



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
